name: vote-app-pipeline
on: push
env:
    serviceName: vote
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # important to checkout code
      - name: fetching short commit id
        run: |
             commitId=$(echo ${{ github.sha }})
             shortCommitId=${commitId:0:7}
             echo "SHORT_COMMIT_ID=$shortCommitId" >> $GITHUB_ENV
      - name: ACR login
        uses: docker/login-action@v3
        with:
            registry: ${{secrets.ACR_LOGIN_SERVER}}
            username: ${{secrets.ACR_USER_NAME}}
            password: ${{secrets.ACR_PASSWORD}}
      - name: image build
        run: |
             echo "comm id: $shortCommitId" ;docker build  -t ${{secrets.ACR_LOGIN_SERVER}}/$serviceName:$SHORT_COMMIT_ID .
      - name: image push to ACR.
        run: docker push ${{secrets.ACR_LOGIN_SERVER}}/$serviceName:$SHORT_COMMIT_ID
      - name: Load kubeconfig
        env:
            KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA"|base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: verifying cluster access
        run: kubectll get po


