name: vote-app-pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # important to checkout code
      - name: printing commit id
        run: |
             commitId=$(echo ${{ github.sha }})
             shortCommitId=${commitId:0:7}
             echo $shortCommitId