name: vote-app-pipeline
on: push
env:
    serviceName: vote
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # important to checkout code
      - name: fetching short commit id
        run: |
             commitId=$(echo ${{ github.sha }})
             shortCommitId=${commitId:0:7}
             echo $shortCommitId
      - name: ACR login
        uses: docker/login-action@v3
        with:
            registry: ${{secrets.ACR_LOGIN_SERVER}}
            username: ${{secrets.ACR_USER_NAME}}
            password: ${{secrets.ACR_PASSWORD}}
      - name: image build
        run: docker build . -t ${{secrets.ACR_LOGIN_SERVER}}/serviceName:$shortCommitId
      - name: image push to ACR.
        run: docker push ${{secrets.ACR_LOGIN_SERVER}}/serviceName:$shortCommitId
